"""initial schema

Revision ID: 9579fc9c7afa
Revises: 
Create Date: 2026-06-28 14:07:02.777502
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9579fc9c7afa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('company', sa.String(length=160), nullable=True),
    sa.Column('segment', sa.String(length=24), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_external_id'), ['external_id'], unique=True)

    op.create_table('policies',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('backoff_days', sa.JSON(), nullable=False),
    sa.Column('retry_window_days', sa.Integer(), nullable=False),
    sa.Column('escalate_after_step', sa.Integer(), nullable=False),
    sa.Column('base_tone', sa.String(length=40), nullable=False),
    sa.Column('brand_voice', sa.String(length=400), nullable=False),
    sa.Column('auto_send', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('plan_name', sa.String(length=80), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('interval', sa.String(length=12), nullable=False),
    sa.Column('status', sa.Enum('active', 'past_due', 'canceled', name='subscription_status', native_enum=False, length=40), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_external_id'), ['external_id'], unique=True)

    op.create_table('dunning_cases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('subscription_id', sa.String(length=32), nullable=True),
    sa.Column('triggering_payment_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'recovered', 'escalated', 'written_off', 'paused', name='case_status', native_enum=False, length=40), nullable=False),
    sa.Column('failure_code', sa.Enum('insufficient_funds', 'expired_card', 'do_not_honor', 'card_declined', 'lost_or_stolen_card', 'authentication_required', 'processing_error', 'fraud_suspected', name='case_failure_code', native_enum=False, length=40), nullable=False),
    sa.Column('amount_at_risk_minor', sa.Integer(), nullable=False),
    sa.Column('recovered_amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action_label', sa.String(length=120), nullable=True),
    sa.Column('plan', sa.JSON(), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('escalated_to', sa.String(length=40), nullable=True),
    sa.Column('requires_human', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dunning_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dunning_cases_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dunning_cases_status'), ['status'], unique=False)

    op.create_table('dunning_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('case_opened', 'classification', 'retry_scheduled', 'retry_attempted', 'retry_succeeded', 'retry_failed', 'message_drafted', 'message_sent', 'escalated', 'human_review', 'resolved', 'written_off', 'note', name='event_type', native_enum=False, length=40), nullable=False),
    sa.Column('actor', sa.Enum('agent', 'human', 'system', name='event_actor', native_enum=False, length=40), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('payment_id', sa.String(length=32), nullable=True),
    sa.Column('message_id', sa.String(length=32), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['dunning_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dunning_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dunning_events_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dunning_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dunning_events_type'), ['type'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.Enum('email', 'sms', name='message_channel', native_enum=False, length=40), nullable=False),
    sa.Column('tone', sa.Enum('friendly_reminder', 'firm_reminder', 'urgent', 'final_notice', 'credit_control', name='message_tone', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'sent', 'edited', name='message_status', native_enum=False, length=40), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=48), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['dunning_cases.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_customer_id'), ['customer_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('subscription_id', sa.String(length=32), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('succeeded', 'failed', 'pending', 'refunded', name='payment_status', native_enum=False, length=40), nullable=False),
    sa.Column('failure_code', sa.Enum('insufficient_funds', 'expired_card', 'do_not_honor', 'card_declined', 'lost_or_stolen_card', 'authentication_required', 'processing_error', 'fraud_suspected', name='failure_code', native_enum=False, length=40), nullable=True),
    sa.Column('failure_message', sa.String(length=255), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('processor', sa.String(length=16), nullable=False),
    sa.Column('case_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['dunning_cases.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_failure_code'), ['failure_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_subscription_id'), ['subscription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_failure_code'))
        batch_op.drop_index(batch_op.f('ix_payments_external_id'))
        batch_op.drop_index(batch_op.f('ix_payments_customer_id'))
        batch_op.drop_index(batch_op.f('ix_payments_case_id'))

    op.drop_table('payments')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_customer_id'))
        batch_op.drop_index(batch_op.f('ix_messages_case_id'))

    op.drop_table('messages')
    with op.batch_alter_table('dunning_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dunning_events_type'))
        batch_op.drop_index(batch_op.f('ix_dunning_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_dunning_events_case_id'))

    op.drop_table('dunning_events')
    with op.batch_alter_table('dunning_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dunning_cases_status'))
        batch_op.drop_index(batch_op.f('ix_dunning_cases_customer_id'))

    op.drop_table('dunning_cases')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_external_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_customer_id'))

    op.drop_table('subscriptions')
    op.drop_table('policies')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_external_id'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))

    op.drop_table('customers')
    # ### end Alembic commands ###
